version: "3.7"

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8088:80
    links:
      - phpfpm
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONRAINER}
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/

  phpfpm:
    build: docker
    restart: always
    links:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONRAINER}
    working_dir: ${APP_PATH_CONRAINER}

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ${DB_PATH_HOST}:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  composer:
    image: composer
    links:
      - nginx
    volumes:
    - ${APP_PATH_HOST}:${APP_PATH_CONRAINER}
    working_dir: ${APP_PATH_CONRAINER}
    command: composer install